export const LIST_SALONES_COMUNIDAD = "LIST_SALONES_COMUNIDAD";
export const LIST_AVERIAS_SALON = "LIST_AVERIAS_SALON";
export const LIST_CHECKLIST = "LIST_CHECKLIST";
export const CREATE_CHECKLIST = "CREATE_CHECKLIST";
export const DELETE_CHECKLIST = "DELETE_CHECKLIST";